<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/css/normalize.css">
    <link rel="stylesheet" href="/css/universalNavStyle.css">
    <link rel="stylesheet" href="/css/sellerOverview.css">
    <title>Seller Dashboard</title>
</head>
<body>
    <div class="navContainer">
        <div class="menu-burger">
        <input type="checkbox" />
        <svg
            xmlns="http://www.w3.org/2000/svg"
            class="icon icon-tabler icon-tabler-menu-2"
            viewBox="0 0 24 24"
            stroke-width="2"
            stroke="currentColor"
            fill="none"
            stroke-linecap="round"
            stroke-linejoin="round"
        >
        <path stroke="none" d="M0 0h24v24H0z" fill="none" />
        <line x1="4" y1="6" x2="20" y2="6" />
        <line x1="4" y1="12" x2="20" y2="12" />
        <line x1="4" y1="18" x2="20" y2="18" />
        </svg>
        <ul class="menu-burger__item-list">
            <li></li>
            <li></li>
            <li></li>
        </ul>
        </div>
        <div class="navBoxOne">
            <p>YARAH</p>
        </div>
        <div class="navBoxTwo">
            <ul>
                <li>
                    <a href="#">Dropdown</a>
                    <ul>
                        <li><a href="#">Profile</a></li>
                        <li><a href="/sellers/dashboard">Seller Overview</a></li>
                        <li><a href="#">Link 3</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
    <div class="backGroundFlare"></div>
    <div class="sellerStatAndBarContainer">
        <div class="sellerQuickBarContainer">
            <div class="quickBarBox">
                <a href="/sellers/dashboard">Overview</a>
            </div>
            <div class="quickBarBox">
                <a href="/sellers/sellerSold">Sold</a>
            </div>
            <div class="quickBarBox">
                <a href="/sellers/sellerSelling">Selling</a>
            </div>
            <div class="quickBarBox">
                <a href="/sellers/sellerBalance">Balance</a>
            </div>
            <div class="quickBarBox">
                <a href="/sellers/sellerStats">Stats</a>
            </div>
        </div>
        <div class="sellerWeeklyStatOverviewContainer">
            <div class="sellerCreateListing">
                <div class="boxButton">
                    <a href="/sellers/createListing/New">Create Listing</a>
                </div>
                <div class="boxButton">
                    <a href="/sellers/editListing">Edit Listing</a>
                </div>
            </div>
            <div class="sellerWeeklyStats">
                <div class="boxSales">
                    <p>Weekly Sales</p>
                </div>
                <div class="boxRevenue">
                    <p>Revenue</p>
                </div>
            </div>
            <div class="sellerSellingContainer">
                <div class="boxSelling">
                    <p>Selling</p>
                </div>
                <div class="boxSelling"></div>
                <div class="boxSelling"></div>
                <div class="boxSelling"></div>
                <div class="boxSelling"></div>
                <div class="boxSelling"></div>
                <div class="boxSelling"></div>
                <div class="boxSelling"></div>
                <div class="boxSelling"></div>
                <div class="boxSelling"></div>
                <div class="boxSelling"></div>
                <div class="boxSelling"></div>
                <div class="boxSelling"></div>
                <div class="boxSelling"></div>
                <div class="boxSelling"></div>
                <div class="boxSelling"></div>
                <div class="boxSelling"></div>
                <div class="boxSelling"></div>
                <div class="boxSelling"></div>
                <div class="boxSelling"></div>
            </div>
            <div class="sellerSoldContainer">
                <div class="boxSold">
                    <p>Sold</p>
                </div>
                <div class="boxSold"></div>
                <div class="boxSold"></div>
                <div class="boxSold"></div>
                <div class="boxSold"></div>
                <div class="boxSold"></div>
                <div class="boxSold"></div>
                <div class="boxSold"></div>
                <div class="boxSold"></div>
                <div class="boxSold"></div>
                <div class="boxSold"></div>
                <div class="boxSold"></div>
                <div class="boxSold"></div>
                <div class="boxSold"></div>
                <div class="boxSold"></div>
                <div class="boxSold"></div>
                <div class="boxSold"></div>
                <div class="boxSold"></div>
                <div class="boxSold"></div>
                <div class="boxSold"></div>
            </div>
        </div>
    </div>
    <div class="footer">
        <h1>Placer Holder Footer</h1>
        <p>
            The quick, brown fox jumps over a lazy dog. DJs flock by when MTV ax quiz prog. Junk MTV quiz graced by fox whelps. Bawds jog, flick quartz, vex nymphs. Waltz, bad nymph, for quick jigs vex! Fox nymphs grab quick-jived waltz. Brick quiz whangs jumpy veldt fox. Bright vixens jump; dozy fowl quack. Quick wafting zephyrs vex bold Jim. Quick zephyrs blow, vexing daft Jim. Sex-charged fop blew my junk TV quiz. How quickly daft jumping zebras vex. Two driven jocks help fax my big quiz. Quick, Baz, get my woven flax jodhpurs! "Now fax quiz Jack!" my brave ghost pled. Five quacking zephyrs jolt my wax bed. Flummoxed by job, kvetching W. zaps Iraq. Cozy sphinx waves quart jug of bad milk. A very bad quack might jinx zippy fowls. Few quips galvanized the mock jury box. Quick brown dogs jump over the lazy fox. The jay, pig, 
        </p>
    </div>
</body>
</html>