<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/high-fidelity-prototype/customer-prototype/css/normalize.css">
    <link rel="stylesheet" href="/high-fidelity-prototype/customer-prototype/css/universalNavStyle.css">
    <link rel="stylesheet" href="/high-fidelity-prototype/customer-prototype/css/sellerOverview.css">
    <link rel="stylesheet" href="/high-fidelity-prototype/customer-prototype/css/sellerStats.css">
    <title>Customer Stats</title>
</head>

 <script
src="https://cdn.jsdelivr.net/npm/chart.js@4.5.0">
</script> 

<body>
    <div class="navContainer">
        <div class="menu-burger">
        <input type="checkbox" />
        <svg
            xmlns="http://www.w3.org/2000/svg"
            class="icon icon-tabler icon-tabler-menu-2"
            viewBox="0 0 24 24"
            stroke-width="2"
            stroke="currentColor"
            fill="none"
            stroke-linecap="round"
            stroke-linejoin="round"
        >
        <path stroke="none" d="M0 0h24v24H0z" fill="none" />
        <line x1="4" y1="6" x2="20" y2="6" />
        <line x1="4" y1="12" x2="20" y2="12" />
        <line x1="4" y1="18" x2="20" y2="18" />
        </svg>
        <ul class="menu-burger__item-list">
            <li></li>
            <li></li>
            <li></li>
        </ul>
        </div>
        <div class="navBoxOne">
            <p>YARAH</p>
        </div>
        <div class="navBoxTwo">
            <ul>
                <li>
                    <a href="#">Dropdown</a>
                    <ul>
                        <li><a href="#">Profile</a></li>
                        <li><a href="/sellers/dashboard.ftlh">Seller Overview</a></li>
                        <li><a href="#">Link 3</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
    <div class="backGroundFlare"></div>
    <div class="sellerStatAndBarContainer">
        <div class="sellerQuickBarContainer">
            <div class="quickBarBox">
                <a href="/high-fidelity-prototype/customer-prototype/sellerOverview.html">Overview</a>
            </div>
            <div class="quickBarBox">
                <a href="/high-fidelity-prototype/customer-prototype/selllerSold.html">Sold</a>
            </div>
            <div class="quickBarBox">
                <a href="/high-fidelity-prototype/customer-prototype/sellerSelling.html">Selling</a>
            </div>
            <div class="quickBarBox">
                <a href="/high-fidelity-prototype/customer-prototype/sellerBalance.html">Balance</a>
            </div>
            <div class="quickBarBox">
                <a href="/high-fidelity-prototype/customer-prototype/sellerStats.html">Stats</a>
            </div>
        </div>
        <div class="sellerStatOverviewContainer">
            <p>Weekly Sales</p>
            <img src="/high-fidelity-prototype/customer-prototype/images/svgBarChart.jpeg" alt="">
            <p>Customer Views Of Your Listings</p>
            <img src="/high-fidelity-prototype/customer-prototype/images/svgLineChart.jpeg" alt="">
        </div>
    </div>
    <div class="footer">
        <h1>Placer Holder Footer</h1>
        <p>
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Magni nulla officiis reiciendis ad necessitatibus, quibusdam, optio, repudiandae quae quisquam labore fugit error aut maiores officia saepe atque nobis aspernatur et. Necessitatibus, illum! Et officiis iure cum, porro culpa voluptatem magnam perspiciatis nisi soluta veniam exercitationem dolorum. Labore eum nisi voluptatem!
        </p>
    </div>
</body>
</html>